### ISSUE TITLE
Any Information for Number of Iteration Selection

### ISSUE THREAD

**Issue by night-chen** [BaeHeeSun/NPC#1]
Hi authors, I am ver interested in your exciting work. However, I have some questions about the number of iterations selection. From the repo, you seem to choose to use 10 as total_iter by default. Can you provide more reasons why 10 is selected and is this the optimal selection for the experiments? I did not find related clarifications in your paper. Sorry for the interruption!

**Comment by SJShin-AI** [comment]
Hi,

thanks for your attention on our paper. 
In our experiment, total_iter is the number of epochs for training NPC, which is our main model. We empirically confirmed that the training of NPC converges in 10 epochs in most cases. Hence, we set total_iter = 10 for all experimental cases without further hyper-parameter tuning. We conjecture that the performance of NPC could be improved with further experiments on different total_iter. 

Best,
Seungjae.

**Comment by night-chen** [comment]
Thank you very much for your comments! That helps a lot.
